##动态权限配置文件
#List<Map<String, String>>
permission-config:
  perms:
    - url: /logout
      permission: anon
    - url: /login
      permission: anon
    - url: /assets/**
      permission: anon
    - url: /images/**
      permission: anon
    - url: /js/**
      permission: anon
    - url: /index.html
      permission: anon
    - url: /loginResource/login
      permission: anon
    - url: /**
      permission: kickout,user